/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Ale
 * Created: 8-mag-2016
 */

CREATE TABLE conto 
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saldo FLOAT
);

CREATE TABLE cliente 
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(32),
    cognome VARCHAR(32),
    username VARCHAR(32),
    password VARCHAR(32),
    idConto INTEGER,
    FOREIGN KEY (idConto) REFERENCES conto(id)
);




CREATE TABLE venditore
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(32),
    cognome VARCHAR(32),
    username VARCHAR(32),
    password VARCHAR(32),
    idConto INTEGER,
    FOREIGN KEY (idConto) REFERENCES conto(id)
);


CREATE TABLE oggetto
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(64),
    url VARCHAR(128),
    descrizione VARCHAR(1024),
    price FLOAT,
    q INTEGER,
    idVenditore INTEGER,
    FOREIGN KEY (idVenditore) REFERENCES venditore(id)
);






INSERT INTO oggetto (id, nome, descrizione, url, price, q, idVenditore)
VALUES 
    (default, 
     'Scarpa tacco Bm2004', 
     'Colore: Celeste. Materiale suola: Gomma. Altezza tacco: 14 cm. Tipo di tacco: Tacco A Spillo. Composizione materiale: Sintetico. Uso: Ottime per essere eleganti al mare e in piscina.',
     'IMG/ta.png',
     599.99,
     13,
     1
    ),
    
    (default,
    'Scarpa antinfortunistica mod.3796',
    'Colore: Nero. Tomaia: Vitello Scamosciato. Fodera: Air Mesh. Suola: Poliuterano e Gomma. Puntale: Alluminio mis.10. Lamina: Non metallica. Plantare: Eva forata. ',
    'IMG/ant1.png',
    120.00,
    3,
    2
    ),

    (default,
     'Scarpa tacco mod. XD-acrobat',
     'Materiale esterno: Sintetico. Altezza tacco: 25 cm. Tipo di tacco: Tacco a spillo. Composizione materiale: Sintetico effetto pelle/camoscio.',
     'IMG/tacco.png',
     985.00,
     7,
     1
    ),
    
    (default,
    'Skechers Prospeed 52086 BKSL',
    'Materiale esterno: Sintetico. Fodera: Sintetico. Materiale suola: Gomma. Chiusura: Stringata. Peso articolo: 340 g.',
    'IMG/sport.png',
    74.90,
    11,
    2
    ),

    (default,
    'Ecco sandalo uomo',
    'Materiale esterno: Pelle. Fodera: Sintetico. Materiale suola: Plastica. Chiusura: A strappo. Altezza tacco: 2 cm. Tipo di tacco: Senza tacco. Composizione materiale: Pelle nabuk/olio Nubuc. Calzata: Vestibilità normale. Larghezza scarpa: Normale',
    'IMG/san.png',
    34.90,
    2,   
    2
    ),

    (default,
    'Scarpa Prada mod.666',
    'Materiale esterno: Pelle. Fodera: Pelle. Materiale suola: Gomma. Chiusura: Stringata',
    'IMG/eleg.png',
    999.99,
    5,   
    2
    ),

    (default,
    'Scarpa tacco mod.E710',
    'Materiale suola: Gomma e Acciaio. Chiusura: Senza chiusura. Altezza tacco: 16 cm. Tipo di tacco: Tacco A Spillo',
    'IMG/tac.png',
    1200.99,
    1,   
    1
    ),

    (default,
    'Scarpe da ginnastica luminose I Minions',
    'Divertenti, blu e gialli... hai indovinato? Ma sì, sono I Minions!. - Scarpe da ginnastica I Minions. - Chiusura con 2 cinturini a strappo di vernice. - Inserti effetto mesh. - Patch effetto plastificato I Minions. - Tacca di flessione davanti. - Suola antiscivolo',
    'IMG/bimbo.png',
    45.00,
    17,   
    2
    );



INSERT INTO conto (id,saldo)
VALUES (default,1220.05),
       (default,95.30),    
       (default,1500.00),  
       (default,300.99),   
       (default,40000.00); 

INSERT INTO cliente (id, nome, cognome, username, password, idConto)
VALUES (default,'Alessandro','Mura','almura','0',1),
       (default,'Petra','Pirastu','petrap','1',2),
       (default,'Nobume','Smith','NBS','2',3);

INSERT INTO venditore (id, nome, cognome, username, password, idConto)
VALUES (default,'Manila','Rossi','maniR','m',4),
       (default,'Ilario','Sakata','jss','b',5);


/*
--aggiungi nuovo oggetto--------------------------------
INSERT INTO oggetto (id, nome, descrizione, url, price, q, idVenditore)
VALUES (default, '',  '','',,,--idVenditore
    );
   
modifica elemento-------------------------------------

UPDATE oggetto SET nome='ddd', descrizione='', url='', price=, q=
WHERE id=1 ;

elimina elemento-----------------------------------------

DELETE FROM oggetto WHERE id=; 

dati di tutti gli oggetti--------------------------------------

SELECT * FROM oggetto;


Venditore specifico---------------------------

SELECT oggetto.id, oggetto.nome, oggetto.descrizione, oggetto.url, oggetto.price, oggetto.q 
FROM oggetto 
JOIN venditore ON oggetto.IdVenditore=venditore.id
WHERE venditore.id=1;


conto di un venditore---------------------------

SELECT saldo
FROM conto
JOIN venditore ON conto.id=venditore.IDCONTO
WHERE venditore.id=2;


prezzo di un oggetto--------------------


SELECT price
FROM oggetto
WHERE id=10;



conto di un cliente---------------------


SELECT saldo
FROM conto
JOIN cliente ON conto.id=cliente.IDCONTO
WHERE cliente.id=2;


modificare il saldo di un conto------------------------

UPDATE conto SET saldo=0.25
WHERE id=1 ;

















